services:
  publisher-agent:
    profiles:
      - services
    build:
      context: .
      dockerfile: docker/images/Dockerfile
      args:
        SERVICE: "publisher_agent"
    command:
      [
        "start",
        "-c",
        "/etc/pull_config.json",
        "-k",
        "/etc/keys.json",
      ]
    volumes:
      - "./configs/pull_config.json:/etc/pull_config.json"
      - "./configs/keys.json:/etc/keys.json"
    environment:
      - STORK_API_KEY=${STORK_API_KEY}
      - STORK_WEBSOCKET_URL=${STORK_WEBSOCKET_URL}
      - LOG_LEVEL=${LOG_LEVEL:-info}

  data-provider:
    profiles:
      - services
    build:
      context: .
      dockerfile: docker/images/Dockerfile
      args:
        SERVICE: "data_provider"
    command:
      [
        "start",
        "-c",
        "/etc/data_provider_config.json",
        "--verbose"
      ]
    volumes:
      - "./configs/data_provider_config.json:/etc/data_provider_config.json"
    environment:
      - DATA_PROVIDER_PORT=${DATA_PROVIDER_PORT:-8080}
      - DATA_PROVIDER_HOST=${DATA_PROVIDER_HOST:-localhost}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${DATA_PROVIDER_PORT:-8080}:${DATA_PROVIDER_PORT:-8080}"

  evm-pusher:
    profiles:
      - services
    build:
      context: .
      dockerfile: docker/images/Dockerfile
      args:
        SERVICE: "chain_pusher"
    command:
      [
        "evm",
        "-w",
        "${STORK_WEBSOCKET_URL:-wss://api.jp.stork-oracle.network}",
        "-a",
        "${STORK_API_KEY}",
        "-c",
        "${EVM_RPC_URL:-https://test-rpc.plumenetwork.xyz}",
        "-x",
        "${EVM_CONTRACT_ADDRESS:-0xacc0a0cf13571d30b4b8637996f5d6d774d4fd62}",
        "-f",
        "/etc/asset-config.yaml",
        "-m",
        "/etc/private-key.secret",
        "-b",
        "${CHAIN_PUSHER_BATCH_SIZE:-5}",
      ]
    volumes:
      - "./configs/asset-config.yaml:/etc/asset-config.yaml"
      - "./configs/private-key.secret:/etc/private-key.secret"
    environment:
      - STORK_API_KEY=${STORK_API_KEY}
      - STORK_WEBSOCKET_URL=${STORK_WEBSOCKET_URL}
      - EVM_RPC_URL=${EVM_RPC_URL}
      - EVM_CONTRACT_ADDRESS=${EVM_CONTRACT_ADDRESS}
      - LOG_LEVEL=${LOG_LEVEL:-info}

  evm-contract:
    profiles:
      - integration
    build:
      context: .
      dockerfile: docker/images/evm.Dockerfile
      args:
        STORK_PUBLIC_KEY: ${STORK_PUBLIC_KEY:-0xC4A02e7D370402F4afC36032076B05e74FF81786}
    ports:
      - "8545:8545"
    healthcheck:
      test:
        [
          "CMD",
          "/bin/sh",
          "-c",
          "wget --quiet --post-data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' --header 'Content-Type: application/json' -O - http://127.0.0.1:8545 | grep result"
        ]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 2s
